### ISSUE TITLE
Update dependency to Ecto 3 ?

### ISSUE THREAD

**Issue by speeddragon** [crbelaus/trans#56]
Do you think there is any incompatibility with Ecto 3 ? I think this should support it.

Thanks.

**Comment by beno** [comment]
+1, I can't use trans in my phx 1.4 app, unless I explicitly override the ecto 3.0 dependency. Let's see if I run into trouble.

    $ mix deps.get
   ...
    Failed to use "ecto" because
       phoenix_ecto (version 4.0.0) requires ~> 3.0
       trans (versions 2.0.0 to 2.0.4) requires ~> 2.1 *

**Comment by crbelaus** [comment]
@speeddragon, @beno I am addressing the Ecto 3.0 update in PR #57

**Comment by crbelaus** [comment]
[Trans 2.1][1] is already published in hex.pm. It supports Ecto 3.0 and does not require any changes to client code.

Thank you for your patience! :beers: 

[1]: https://hex.pm/packages/trans
