### ISSUE TITLE
Additional translation method without fallback

### ISSUE THREAD

**Issue by AntonTrapp** [crbelaus/trans#58]
Additional to

`Trans.Translator.translate(article, :title, :de)` -> fallback, returns the default

something like

`Trans.Translator.translate!(article, :title, :de)` -> should raise an error

would be useful.

PS: Nice library, thank you. Already was in love with the RoR version :)

**Comment by crbelaus** [comment]
This can be a great improvement easy to implement. I could build a pull request myself, but I don't have too much time at the moment.

I am open to pull requests, so in the meantime anybody can feel free to submit one implementing this improvement. If no pull request arrives I will look into it myself when I have the time.

Thank you very much @AntonTrapp :hugs:
