### ISSUE TITLE
Phoenix demo project?

### ISSUE THREAD

**Issue by mrcasals** [crbelaus/trans#60]
Hi!

I tried looking in your repos, but I couldn't find any demo on how to use Trans with Phoenix forms, and I don't know how to achieve a form that returns the data structure Trans requires.

Can we have a demo on how to use Trans with Phoenix?

Thanks!!

**Comment by crbelaus** [comment]
Trans is meant to be an independent library not attached to Phoenix. It can be used with it, but won't depend on it.

Thank you for your suggestion @mrcasals :raised_hands:  If you want to, you can send a PR demoing or documenting the integration. It would make a great addition to the project.
