### ISSUE TITLE
accept `locale` also as string

### ISSUE THREAD

**Issue by sfusato** [crbelaus/trans#62]
I'm usually using `Trans` together with `Gettext.get_locale()`.

`Gettext.get_locale()` returns the locale as a string (eg. `"es"`), while `Trans.Translator.translate/3` only accepts an atom:
`Trans.Translator.translate(article, :title, :es)`

It would be nice to be able to use it as below directly:
`Trans.Translator.translate(article, :title, Gettext.get_locale())`

**Comment by crbelaus** [comment]
This is a great suggestion. We are working on a solution in the pull request #63 . You can set yourself as a watcher if you want notifications about the development.

Thank you very much @sfusato :raised_hands:
