### ISSUE TITLE
Issue with cyrillic search

### ISSUE THREAD

**Issue by HereComesTheRainAgain** [crbelaus/trans#68]
Hi, I have tried to add translations for Serbian and Russian language and case insensitive search does not work.

Any idea why that might be a case?

**Comment by HereComesTheRainAgain** [comment]
Here is the sample of translations map:
`{"de": {"name": "Kaffee"}, "ru": {"name": "Кафа"}, "sr": {"name": "Кафа"}}`

I can do a search for 'KaFfEe', but 'КаФа' does not work.

**Comment by HereComesTheRainAgain** [comment]
I have solved it by manually writing ilike query with fragment:
`ilike(fragment("?->?->>'name' collate \"en_US\"", i.translations, ^lang), ^ilike)`

It works when collation is set to `en_US`.

Could you include support for this in next version,
so I can switch back to `translate`?

**Comment by crbelaus** [comment]
This behaviour is not Trans specifiy and has to do with [how PostgreSQL manages collations](https://www.postgresql.org/docs/12/collation.html).

> The default collation selects the LC_COLLATE and LC_CTYPE values specified at database creation time. The C and POSIX collations both specify “traditional C” behavior, in which **only the ASCII letters “A” through “Z” are treated as letters, and sorting is done strictly by character code byte values**.

I am not sure if this is something that should be supported directly by Trans, although a pull request would be appreciated and we could start talking about implementation specifics with a concrete example.

**Comment by crbelaus** [comment]
As this behaviour is not Trans specific, I am going to close this issue.

Thanks for your detailed report @HereComesTheRainAgain ❤️. If you want to open a PR that improves the documentation in this reward it would be more than welcome.
