### ISSUE TITLE
Using changesets with trans

### ISSUE THREAD

**Issue by davemccrea** [crbelaus/trans#75]
The docs do mention how to use a changeset with trans. My code is as follows:

```elixir
defmodule Company.Product do
  use Ecto.Schema
  use Trans, translates: [:name, :description]
  import Ecto.Changeset

  alias __MODULE__

  defmodule Translation do
    use Ecto.Schema

    @primary_key false
    embedded_schema do
      field :name, :string
      field :description, :string
    end
  end

  schema "products" do
    field :name, :string
    field :description, :string
    field :price, :integer
    field :image_slug, :string

    embeds_one :translations, Translations, on_replace: :update, primary_key: false do
      embeds_one :sv, Product.Translation, on_replace: :update
      embeds_one :fi, Product.Translation, on_replace: :update
    end

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:name, :description, :price, :image_slug])
    |> cast_embed(:translations) # is cast_embed the right option here?
    |> validate_required([:name, :description, :price, :image_slug])
  end
end
```

Using `cast_embed` returns the following error:

```
** (UndefinedFunctionError) function Company.Product.Translations.changeset/2 is undefined or private. Did you mean:
     
           * __changeset__/0
```

What is the correct way to use trans with a changeset?

**Comment by darth-jorge** [comment]
I was looking into the test files and I found an example:
https://github.com/crbelaus/trans/blob/v2.3.0/test/support/models/article.ex 

Hope this helps :D

**Comment by crbelaus** [comment]
> I was looking into the test files and I found an example: https://github.com/crbelaus/trans/blob/v2.3.0/test/support/models/article.ex
> 
> Hope this helps :D

This is correct. In this particular case you should create a `translations_changeset` and use it in the `cast_embed` function call. Just like we do [here](https://github.com/crbelaus/trans/blob/6150d309dd2116c6838a5bb051dca5b171e681cf/test/support/models/article.ex#L35).

I'm closing this issue since this should answer the original question. Feel free to open a pull request to improve the documentation 🙇
